name: "Build & Test"

on: 
  workflow_dispatch:
  push: 
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3
      - name: Setup .NET
        uses: actions/setup-dotnet@3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore src/CleanArchitectureProjectTemplate.sln

      - name: Build
        run: dotnet build src/CleanArchitectureProjectTemplate.sln --configuration Release --no-restore

      - name: Test 
        run: dotnet test src/CleanArchitectureProjectTemplate.sln --configuration Release --no-restore --no-build  
      
  
